---
node_image: &node_image
  image: lowess/preact-cli:latest

hugo_env: &hugo_env
  BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/

when_prod: &when_prod
  when:
    branch: master

kind: pipeline
name: preact-template-pipeline
steps:
  - name: preact-template-rendering
    <<: *node_image
    commands:
      - preact create Lowess/preact-hugo#${DRONE_COMMIT} test-app

  # - name: restore-cache
  #   image: drillster/drone-volume-cache
  #   settings:
  #     restore: true
  #     mount:
  #       - ./node_modules
  #   volumes:
  #     - name: node_cache
  #       path: /cache

  - name: install-preact-app
    <<: *node_image
    commands:
      - cd test-app
      - npm install

  # - name: rebuild-cache
  #   image: drillster/drone-volume-cache
  #   settings:
  #     rebuild: true
  #     mount:
  #       - ./.tox
  #   volumes:
  #     - name: tox_cache
  #       path: /cache

  - name: build-preact-app
    <<: *node_image
    environment:
      <<: *hugo_env
    commands:
      - cd test-app
      - npm run build

  - name: publish-preact-app
    image: plugins/gh-pages
    environment:
      DRONE_REMOTE_URL: git@github.com:${DRONE_REPO}.git
    settings:
      username: Lowess
      ssh_key:
        from_secret: github_ssh_key
      pages_directory: test-app/dist/
    <<: *when_prod

  - name: echo-urls
    image: lowess/drone-tabulate
    environment:
      <<: *hugo_env
    settings:
      headers:
        - URL
      rows:
        -
          - "Github IO"
          - https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/
        -
          - "Custom Domain"
          - $BASE_URL

  - name: notify
    image: plugins/slack
    failure: ignore
    settings:
      channel: drone-ci
      webhook:
        from_secret: slack_webhook
      username: "Drone"
      icon_url: https://pbs.twimg.com/profile_images/573911705505259520/rShq67tG_400x400.png
      template: |
        {{#success build.status}}
          {{ build.link }} {{ build.author }} successfully pushed to {{ build.branch }}
        {{else}}
          {{ build.link }} {{ build.author }} broke the build.
        {{/success}}
    when:
      status: [success, failure]
